import { degrees, metres } from "@/lib/helpers";
import type { IClothFeel } from "@/types/physics";

export const PHYSICS = {
    dataKey: "physics",
    dataVersion: 3,
    boneNamePrefix: "phys_",
    epsilon: { geometry: 1e-12, motion: 1e-9 },
    step: {
        substepsPerFrame: 12,
        referenceFrameSeconds: 1 / 60,
        maxSubsteps: 24,
        maxFrameSeconds: 1 / 30,
        reducedSubstepShare: 1 / 3,
    },
    solver: {
        maxSpeed: metres(12),
        sleepSpeed: metres(0.02),
        sleepSeconds: 0.5,
        wakeSpeed: metres(0.12),
        wakeAngularSpeed: degrees(12),
        floorClearance: metres(0.02),
        collisionPasses: 2,
    },
    reference: {
        linearInertia: 0.6,
        angularInertia: 0.6,
        flingScale: 1,
        maxLinearSpeed: metres(8),
        maxAngularSpeed: degrees(540),
        teleportDistance: metres(1.5),
        teleportAngle: degrees(90),
    },
    environment: {
        gravity: metres(9.81),
        wind: {
            direction: [0.6, 0, 0.8],
            base: metres(0.02),
            gustAmplitude: metres(0.04),
            gustHertz: 0.35,
        },
    },
    impulse: { speedPerStrength: metres(0.35), minimumPushLengthSquared: 1e-8 },
    lod: { fullMetres: metres(15), reducedMetres: metres(40) },
    cloth: {
        damping: 1.2,
        stretchCompliance: 1e-7,
        bendCompliance: 1e-5,
        gravityScale: 1,
        windExposure: 1,
        tetherScale: 1.03,
        leashMax: metres(1.3),
        leashCurve: 1,
        backstopRadius: metres(0.3),
        backstopOffset: metres(0.01),
        collisionThickness: metres(0.012),
        deflectionMargin: metres(0.01),
        deflectionSoftness: metres(0.06),
        friction: 4,
        impulseScale: 1,
    } satisfies IClothFeel,
};
