import { pair } from "@/lib/helpers";

export const GRASS = {
    rings: [
        { outerRadius: 22, cellSize: 0.28, segments: 4 },
        { outerRadius: 40, cellSize: 0.42, segments: 2 },
        { outerRadius: 62, cellSize: 0.62, segments: 1 },
    ],
    ringCrossfadeWidth: 4,
    bladeHeightRange: pair(0.4, 1),
    bladeWidth: 0.1,
    bladeTaperExponent: 0.55,
    bladeSizeGainAtHorizon: 1.7,
    leanRange: pair(0.06, 0.3),
    curlRange: pair(0.12, 0.42),
    tintRange: pair(0.82, 1.16),
    fadeStartRatio: 0.86,
    tipLightnessGain: 0.26,
    tipHueShift: 0.04,
    rootDarken: 0.74,
    sunWrap: 0.45,
    sunGain: 0.55,
    ambientGain: 0.9,
    windStrength: 0.13,
    windFrequency: 1.5,
    windScale: 0.11,
    windGustScale: 0.02,
    corridorRejectThreshold: 0.3,
};

export const VEGETATION = {
    treeDensity: 0.00042,
    fillerDensity: 0.00036,
    groundCoverDensity: 0.00135,
    treeSpeciesPerBand: 5,
    fillerSpeciesPerBand: 4,
    groundCoverSpeciesPerBand: 6,
    outerDensityFactor: 0.55,
    maximumPerBand: 3000,
    treeSlopeLimit: 0.7,
    fillerSlopeLimit: 1.1,
    grassSlopeLimit: 0.8,
    treeScaleBoost: pair(1.1, 1.7),
    edgePadding: 2,
    carveRejectThreshold: 0.1,
    groundBite: 0.02,
};

export const PROP_PLACEMENT = {
    landmarkDensity: 0.00028,
    structureDensity: 0.0012,
    clutterDensity: 0.014,
    anchorDensity: 0.00016,
    landmarkSpeciesPerRegion: 3,
    structureSpeciesPerRegion: 4,
    clutterSpeciesPerRegion: 7,
    typicalFileCount: 20,
    minimumRichness: 0.5,
    maximumRichness: 2,
    referenceScatterPropsPerFile: 0.45,
    combatArenaRatio: 0.35,
    clusterRadiusRatio: 0.22,
    edgeBiasExponent: 0.4,
    entranceMouthClearanceRatio: 1.9,
    entranceLaneWidthRatio: 1.1,
    clutterEntranceClearanceFactor: 0.45,
    clutterHuddledAgainstPropRatio: 0.4,
    clutterHuddleRadius: 3,
    clearanceRelaxationSteps: [1, 0.6, 0.35],
    separationGap: 1,
    placementAttempts: 10,
};

export const CORRIDOR_PROPS = {
    anchorsPerUnitLength: 0.022,
    minimumAnchorsPerCorridor: 1,
    maximumAnchorsPerCorridor: 8,
    spineJitter: 0.35,
    lateralMarginRatio: 0.7,
    lateralSpread: 16,
    clusterRadius: 5,
    propsPerAnchor: pair(2, 5),
    speciesPerRealm: 6,
    regionKeepOut: 6,
    slopeLimit: 0.9,
    carveRejectThreshold: 0.25,
    scaleBoost: pair(1, 1.4),
    placementAttempts: 8,
};
