import { pair } from "@/lib/helpers";

export const GRASS = {
    levelRadii: [15, 32, 68],
    tuftSpacing: 0.38,
    bladesPerTuft: 3,
    bladeHeightRange: pair(0.5, 1),
    bladeWidth: 0.1,
    bladeTaperExponent: 0.6,
    bladeCurvature: 0.6,
    leanRange: pair(0.15, 0.6),
    steepGroundLimit: 0.9,
    carvedPathLimit: 0.3,
    wind: {
        heading: 0.95,
        bendSpread: 1.1,
        waveLength: 14,
        waveSpeed: 1.1,
        sway: 0.45,
        flutter: 0.15,
        flutterSpeed: 5.5,
    },
    tone: {
        patchNoiseScale: 0.03,
        tuftToneWeight: 0.45,
        tintRange: pair(0.82, 1.1),
        lushHueShift: 0.03,
        dryHueShift: -0.05,
        tipLightnessGain: 0.18,
        rootDarken: 0.45,
    },
    light: {
        sunWrap: 0.42,
        sunGain: 0.55,
        ambientGain: 0.85,
        baseOcclusion: 0.42,
        tipSheen: 0.06,
    },
};

export const VEGETATION = {
    treeDensity: 0.00021,
    fillerDensity: 0.00018,
    groundCoverDensity: 0.00067,
    treeSpeciesPerBand: 5,
    fillerSpeciesPerBand: 4,
    groundCoverSpeciesPerBand: 6,
    outerDensityFactor: 0.55,
    maximumPerBand: 1500,
    treeSlopeLimit: 0.7,
    fillerSlopeLimit: 1.1,
    grassSlopeLimit: 0.8,
    treeScaleBoost: pair(1.1, 1.7),
    edgePadding: 2,
    carveRejectThreshold: 0.1,
    groundBite: 0.02,
};

export const LEDGE = {
    stepRiseOfJumpApex: 0.7,
    maxAlongCorridorRatio: 0.3,
    safeRiseOfJumpApex: 0.95,
    rocksPerStep: 3,
    rockWidthOfCorridorHalfWidth: 0.22,
    rockWidthJitter: 0.45,
    lateralSpreadOfCorridorHalfWidth: 0.75,
    alongSpreadOfRockWidth: 1.6,
    riseJitter: 0.18,
    buriedDepth: 1.5,
};

export const PROP_PLACEMENT = {
    landmarkDensity: 0.00028,
    structureDensity: 0.0012,
    clutterDensity: 0.014,
    anchorDensity: 0.00016,
    landmarkSpeciesPerRegion: 3,
    structureSpeciesPerRegion: 4,
    clutterSpeciesPerRegion: 7,
    typicalFileCount: 20,
    minimumRichness: 0.5,
    maximumRichness: 2,
    referenceScatterPropsPerFile: 0.45,
    combatArenaRatio: 0.35,
    clusterRadiusRatio: 0.22,
    edgeBiasExponent: 0.4,
    entranceMouthClearanceRatio: 1.9,
    entranceLaneWidthRatio: 1.1,
    standingEntranceClearanceFactor: 1,
    clutterEntranceClearanceFactor: 0.45,
    clutterHuddledAgainstPropRatio: 0.4,
    clutterHuddleRadius: 3,
    clearanceRelaxationSteps: [1, 0.6, 0.35],
    separationGap: 1,
    placementAttempts: 10,
    slopeLimit: 0.9,
};

export const CORRIDOR_PROPS = {
    anchorsPerUnitLength: 0.022,
    minimumAnchorsPerCorridor: 1,
    maximumAnchorsPerCorridor: 8,
    spineJitter: 0.35,
    lateralMarginRatio: 0.7,
    lateralSpread: 16,
    clusterRadius: 5,
    propsPerAnchor: pair(2, 5),
    speciesPerRealm: 6,
    regionKeepOut: 6,
    slopeLimit: 0.9,
    carveRejectThreshold: 0.25,
    scaleBoost: pair(1, 1.4),
    placementAttempts: 8,
};
