import { ChapterTheme } from "@/types/realm";
import type { IThemeManifest, IThemeProp } from "@/types/theme";
import {
    CANOPY_TREES,
    PINE_TREES,
    TWISTED_TREES,
    DEAD_TREES,
    BOULDERS,
    ROCK_SLABS,
    ROCK_CHUNKS,
    BUSHES,
    BROAD_PLANTS,
    GRASS_TUFTS,
    UNDERGROWTH,
    FLOWERS,
    MUSHROOMS,
    PEBBLES,
    FALLEN_PETALS,
} from "@/themes/PropCatalogue";

export const WOODLAND_PROPS: IThemeProp[] = [
    ...CANOPY_TREES,
    ...PINE_TREES,
    ...TWISTED_TREES,
    ...DEAD_TREES,
    ...BOULDERS,
    ...ROCK_SLABS,
    ...ROCK_CHUNKS,
    ...BUSHES,
    ...BROAD_PLANTS,
    ...GRASS_TUFTS,
    ...UNDERGROWTH,
    ...FLOWERS,
    ...MUSHROOMS,
    ...PEBBLES,
    ...FALLEN_PETALS,
];

export const WOODLAND_MANIFEST: IThemeManifest = {
    theme: ChapterTheme.Woodland,
    scatterPropsPerFile: 0.6,
    props: WOODLAND_PROPS,
    environment: {
        sky: {
            zenith: "#3d6480",
            middle: "#8fadb8",
            horizon: "#e6d9ba",
            abyss: "#22303c",
            glow: "#f2b06a",
            sun: "#ffe6bc",
            sunElevation: 0.62,
            sunAzimuth: 0.7,
            sunSize: 0.026,
            glowFalloff: 9,
            hazeStrength: 3,
        },
        lighting: {
            keyColor: "#ffe8c4",
            keyIntensity: 1.6,
            rimColor: "#9cb8d8",
            rimIntensity: 0.55,
            skyFill: "#b8ccd4",
            groundFill: "#59502e",
            hemisphereIntensity: 0.65,
        },
        fogDensity: 0.0052,
        outlineColor: "#2a2318",
        terrain: {
            wildColor: "#4e6238",
            rockColor: "#6b6455",
            peakColor: "#a8b29a",
            wildElevation: 11,
            wildRelief: 5,
            mountainHeight: 30,
            featureSize: 90,
            ruggedness: 0.35,
            slopeShade: 0.45,
        },
    },
};

export const HIGHLANDS_PROPS: IThemeProp[] = [
    ...PINE_TREES,
    ...TWISTED_TREES,
    ...DEAD_TREES,
    ...BOULDERS,
    ...ROCK_SLABS,
    ...ROCK_CHUNKS,
    ...GRASS_TUFTS,
    ...PEBBLES,
];

export const HIGHLANDS_MANIFEST: IThemeManifest = {
    theme: ChapterTheme.Highlands,
    scatterPropsPerFile: 0.4,
    props: HIGHLANDS_PROPS,
    environment: {
        sky: {
            zenith: "#24548c",
            middle: "#6b96be",
            horizon: "#e4ecef",
            abyss: "#1a2734",
            glow: "#ffd7a4",
            sun: "#fff4dc",
            sunElevation: 0.85,
            sunAzimuth: 5.4,
            sunSize: 0.02,
            glowFalloff: 6,
            hazeStrength: 2,
        },
        lighting: {
            keyColor: "#ffffff",
            keyIntensity: 1.8,
            rimColor: "#8fb6d8",
            rimIntensity: 0.7,
            skyFill: "#cfdee6",
            groundFill: "#4c5a60",
            hemisphereIntensity: 0.7,
        },
        fogDensity: 0.0042,
        outlineColor: "#1a2028",
        terrain: {
            wildColor: "#43563e",
            rockColor: "#5f6a70",
            peakColor: "#e2e9ee",
            wildElevation: 15,
            wildRelief: 7,
            mountainHeight: 46,
            featureSize: 80,
            ruggedness: 0.7,
            slopeShade: 0.5,
        },
    },
};

export const RUINS_PROPS: IThemeProp[] = [
    ...TWISTED_TREES,
    ...DEAD_TREES,
    ...BOULDERS,
    ...ROCK_SLABS,
    ...ROCK_CHUNKS,
    ...UNDERGROWTH,
    ...MUSHROOMS,
    ...PEBBLES,
];

export const RUINS_MANIFEST: IThemeManifest = {
    theme: ChapterTheme.Ruins,
    scatterPropsPerFile: 0.35,
    props: RUINS_PROPS,
    environment: {
        sky: {
            zenith: "#3b4b56",
            middle: "#7c8a88",
            horizon: "#c6bcae",
            abyss: "#1d242a",
            glow: "#d09a70",
            sun: "#f4d6ae",
            sunElevation: 0.52,
            sunAzimuth: 4.2,
            sunSize: 0.03,
            glowFalloff: 10,
            hazeStrength: 3.6,
        },
        lighting: {
            keyColor: "#f0d8b8",
            keyIntensity: 1.4,
            rimColor: "#7f95a0",
            rimIntensity: 0.65,
            skyFill: "#9caaa8",
            groundFill: "#463f33",
            hemisphereIntensity: 0.6,
        },
        fogDensity: 0.0078,
        outlineColor: "#1c1a16",
        terrain: {
            wildColor: "#525d44",
            rockColor: "#6e6a62",
            peakColor: "#a49c8e",
            wildElevation: 10,
            wildRelief: 4,
            mountainHeight: 26,
            featureSize: 75,
            ruggedness: 0.6,
            slopeShade: 0.55,
        },
    },
};

export const SETTLEMENT_PROPS: IThemeProp[] = [
    ...CANOPY_TREES,
    ...PINE_TREES,
    ...BUSHES,
    ...BROAD_PLANTS,
    ...GRASS_TUFTS,
    ...FLOWERS,
    ...ROCK_SLABS,
    ...PEBBLES,
];

export const SETTLEMENT_MANIFEST: IThemeManifest = {
    theme: ChapterTheme.Settlement,
    scatterPropsPerFile: 0.45,
    props: SETTLEMENT_PROPS,
    environment: {
        sky: {
            zenith: "#56718a",
            middle: "#a2b0b8",
            horizon: "#ded2c0",
            abyss: "#2a2f38",
            glow: "#e8bc90",
            sun: "#ffeacc",
            sunElevation: 0.75,
            sunAzimuth: 2.1,
            sunSize: 0.022,
            glowFalloff: 7,
            hazeStrength: 2.4,
        },
        lighting: {
            keyColor: "#ffeed6",
            keyIntensity: 1.5,
            rimColor: "#a8b6c4",
            rimIntensity: 0.5,
            skyFill: "#bfc6c8",
            groundFill: "#61533e",
            hemisphereIntensity: 0.7,
        },
        fogDensity: 0.0062,
        outlineColor: "#241d16",
        terrain: {
            wildColor: "#63704b",
            rockColor: "#7a7161",
            peakColor: "#b8b09c",
            wildElevation: 8,
            wildRelief: 3,
            mountainHeight: 20,
            featureSize: 110,
            ruggedness: 0.2,
            slopeShade: 0.4,
        },
    },
};
